[package]

name = "texture_packer"
version = "0.1.0"
authors = ["Coeuvre <coeuvre@gmail.com>"]
keywords = ["texture", "packer", "piston"]
description = "A library for texture packing"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/texture_packer.git"
homepage = "https://github.com/PistonDevelopers/texture_packer"

[lib]

name = "texture_packer"

[dependencies.image]
version = "0.3.12"

